- name: Настроить сетевые параметры
  hosts: kubernetes
  become: yes
  tasks:
    - name: Включить модули ядра
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          br_netfilter
          ip_vs
          ip_vs_rr
          ip_vs_wrr
          ip_vs_sh
          overlay

    - name: Загрузить модули ядра
      command: modprobe {{ item }}
      loop:
        - br_netfilter
        - ip_vs
        - ip_vs_rr
        - ip_vs_wrr
        - ip_vs_sh
        - overlay

    - name: Настроить sysctl для сети
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1

    - name: Применить sysctl
      command: sysctl --system