- name: Install Calico Network Plugin
  hosts: master
  become: yes
  tasks:
    - name: Deploy Tigera Operator
      command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml

    - name: Download custom-resources.yaml
      get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/custom-resources.yaml
        dest: /root/custom-resources.yaml

    - name: Modify Pod CIDR in custom-resources.yaml
      replace:
        path: /root/custom-resources.yaml
        regexp: 'cidr: 192\.168\.0\.0\/16'
        replace: 'cidr: 10.244.0.0/16'

    - name: Apply Calico configuration
      command: kubectl create -f /root/custom-resources.yaml

    - name: Verify Calico pods
      command: kubectl get pods -n calico-system
      register: calico_pods
      changed_when: false

    - debug:
        msg: "{{ calico_pods.stdout_lines }}"