- name: Install and configure Containerd
  hosts: kubernetes
  become: yes
  tasks:
    - name: Add Docker repository
      command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install containerd.io
      dnf:
        name: containerd.io
        state: present

    - name: Create containerd config directory
      file:
        path: /etc/containerd
        state: directory

    - name: Generate default containerd config
      shell: containerd config default | tee /etc/containerd/config.toml

    - name: Enable SystemdCgroup
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Restart and enable containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes

    - name: Verify containerd status
      command: systemctl status containerd
      register: containerd_status
      changed_when: false

    - debug:
        msg: "{{ containerd_status.stdout_lines }}"