- name: Join Worker Nodes to Kubernetes Cluster
  hosts: workers
  become: yes
  vars:
    join_command: "kubeadm join 172.31.31.113:6443 --token 7s1i13.q82hha6uz5edl57j --discovery-token-ca-cert-hash sha256:2132757305cc784b8bc6f7e8cb88bff1c3884ec8e98a46a369ec7ac269903c42"
  tasks:
    - name: Execute Join Command on Workers
      command: "{{ join_command }}"
      args:
        executable: /bin/bash
      register: join_result
      changed_when: false

    - debug:
        msg: "{{ join_result.stdout_lines }}"