- name: Initialize Kubernetes Master Node
  hosts: master
  become: yes
  tasks:
    - name: Initialize Kubernetes
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_output
      changed_when: false

    - debug:
        msg: "{{ kubeadm_output.stdout_lines }}"

    - name: Save kubeconfig for current user
      shell: |
        mkdir -p ~/.kube
        cp -i /etc/kubernetes/admin.conf ~/.kube/config
        chown $(id -u):$(id -g) ~/.kube/config
      become: yes
      become_user: ec2-user