- name: Настроить hostname на Kubernetes-нодах
  hosts: kubernetes
  become: yes
  tasks:
    - name: Установить hostname на Master Node
      hostname:
        name: "kuber-master"
      when: "'master' in inventory_hostname"

    - name: Установить hostname на Worker Nodes
      hostname:
        name: "{{ 'kuber-node-' ~ (groups['workers'].index(inventory_hostname) + 1) }}"
      when: "'workers' in group_names"

    - name: Перезаписать /etc/hostname
      copy:
        dest: /etc/hostname
        content: "{{ ansible_facts['hostname'] }}\n"