- name: Настроить /etc/hosts
  hosts: kubernetes
  become: yes

  vars:
    hosts_entries:
      - "75.101.206.250 kuber-master"
      - "34.193.149.87 kuber-node-1"
      - "18.213.135.12 kuber-node-2"
      - "44.208.169.137 kuber-node-3"

  tasks:
    - name: Добавить хосты в /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      loop: "{{ hosts_entries }}"