- name: Настроить /etc/hosts
  hosts: kubernetes
  become: yes

  vars:
    hosts_entries:
      - "172.31.31.113 kuber-master"
      - "172.31.20.21 kuber-node-1"
      - "172.31.29.129 kuber-node-2"
      - "172.31.17.92 kuber-node-3"

  tasks:
    - name: Добавить хосты в /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      loop: "{{ hosts_entries }}"